#!/bin/sh
			
./../../mmip-version-incomplete/test-strelm 0  3  0 test-strelm.png
./../../mmip-version-incomplete/test-strelm 1  3  0 test-strelm.png
./../../mmip-version-incomplete/test-strelm 1  6  1 test-strelm.png
./../../mmip-version-incomplete/test-strelm 1  6  2 test-strelm.png
./../../mmip-version-incomplete/test-strelm 7  0  1 test-strelm.png
./../../mmip-version-incomplete/test-strelm 7  0  2 test-strelm.png
./../../mmip-version-incomplete/test-strelm 3  3  6 test-strelm.png
./../../mmip-version-incomplete/test-strelm 6  1  1 test-strelm.png

